// Authentication
export const AUTHENTICATE_SUCCESS = 'AUTHENTICATE_SUCCESS';
export const AUTHENTICATE_FAILURE = 'AUTHENTICATE_FAILURE';

// Users
export const FILTER_USERS_NAME = 'FILTER_USERS_NAME';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAILURE = 'CREATE_USER_FAILURE';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAILURE = 'DELETE_USER_FAILURE';

// Projects
export const FILTER_PROJECTS_TITLE = 'FILTER_PROJECTS_TITLE';
export const CREATE_PROJECT_SUCCESS = 'CREATE_PROJECT_SUCCESS';
export const CREATE_PROJECT_FAILURE = 'CREATE_PROJECT_FAILURE';
export const FETCH_PROJECTS_SUCCESS = 'FETCH_PROJECTS_SUCCESS';
export const FETCH_PROJECTS_FAILURE = 'FETCH_PROJECTS_FAILURE';
export const FETCH_PROJECT_SUCCESS = 'FETCH_PROJECT_SUCCESS';
export const FETCH_PROJECT_FAILURE = 'FETCH_PROJECT_FAILURE';
export const UPDATE_PROJECT_SUCCESS = 'UPDATE_PROJECT_SUCCESS';
export const UPDATE_PROJECT_FAILURE = 'UPDATE_PROJECT_FAILURE';
export const DELETE_PROJECT_SUCCESS = 'DELETE_PROJECT_SUCCESS';
export const DELETE_PROJECT_FAILURE = 'DELETE_PROJECT_FAILURE';

// Project News Articles
export const CREATE_NEWS_ARTICLE_SUCCESS = 'CREATE_NEWS_ARTICLE_SUCCESS';
export const CREATE_NEWS_ARTICLE_FAILURE = 'CREATE_NEWS_ARTICLE_FAILURE';
export const FETCH_NEWS_ARTICLE_SUCCESS = 'FETCH_NEWS_ARTICLE_SUCCESS';
export const FETCH_NEWS_ARTICLE_FAILURE = 'FETCH_NEWS_ARTICLE_FAILURE';
export const FETCH_NEWS_ARTICLES_SUCCESS = 'FETCH_NEWS_ARTICLES_SUCCESS';
export const FETCH_NEWS_ARTICLES_FAILURE = 'FETCH_NEWS_ARTICLES_FAILURE';
export const UPDATE_NEWS_ARTICLE_SUCCESS = 'UPDATE_NEWS_ARTICLE_SUCCESS';
export const UPDATE_NEWS_ARTICLE_FAILURE = 'UPDATE_NEWS_ARTICLE_FAILURE';
export const DELETE_NEWS_ARTICLE_SUCCESS = 'DELETE_NEWS_ARTICLE_SUCCESS';
export const DELETE_NEWS_ARTICLE_FAILURE = 'DELETE_NEWS_ARTICLE_FAILURE';

// Project Discoveries
export const FETCH_DISCOVERY_SUCCESS = 'FETCH_DISCOVERY_SUCCESS';
export const UPDATE_DISCOVERY_FAILURE = 'UPDATE_DISCOVERY_FAILURE';

// Project References
export const FETCH_REFERENCE_SUCCESS = 'FETCH_REFERENCE_SUCCESS';
export const UPDATE_REFERENCE_FAILURE = 'UPDATE_REFERENCE_FAILURE';

// Project Feedbacks
export const FETCH_FEEDBACKS_SUCCESS = 'FETCH_FEEDBACKS_SUCCESS';

// Comments
export const CREATE_COMMENT_SUCCESS = 'CREATE_COMMENT_SUCCESS';
export const CREATE_COMMENT_FAILURE = 'CREATE_COMMENT_FAILURE';
export const FETCH_COMMENTS_SUCCESS = 'FETCH_COMMENTS_SUCCESS';
export const UPDATE_COMMENT_FAILURE = 'UPDATE_COMMENT_FAILURE';
export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS';
export const DELETE_COMMENT_FAILURE = 'DELETE_COMMENT_FAILURE';
export const UPVOTE_COMMENT_SUCCESS = 'UPVOTE_COMMENT_SUCCESS';
export const UPVOTE_COMMENT_FAILURE = 'UPVOTE_COMMENT_FAILURE';
export const DOWNVOTE_COMMENT_SUCCESS = 'DOWNVOTE_COMMENT_SUCCESS';
export const DOWNVOTE_COMMENT_FAILURE = 'DOWNVOTE_COMMENT_FAILURE';
